<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Rafferty.StrategyImporter</AssemblyName>
    <RootNamespace>Rafferty.StrategyImporter</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Rafferty.Core\Rafferty.Core.csproj" />
    <ProjectReference Include="..\..\Rafferty.Shared\Rafferty.Shared.csproj" />
  </ItemGroup>
</Project>

